### ISSUE TITLE
switching version leads to duplicate changes

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#185]
### Context

Switching a version doesn't skip change control and neither applies changes. 

### Task

1. Apply changes in `switchVersion`
2. Skip own change control in `switchVersion`

**Comment by samuelstroschein** [comment]
@felix.haeberle are you down to make a PR for this? 

* unit tests expected

**Comment by NiklasBuchfink** [comment]
@felix.haeberle Any updates on this?
