### ISSUE TITLE
Validate if user is able to push

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/lix-sdk#19]
### Context

Users can't push their changes if the inlang GitHub app is not installed and they can't install it themselves if they are not the repo's owner. They will also lose their translations as there is no export or caching yet.

Related:

* [FINK-40](https://linear.app/opral/issue/FINK-40/the-doc-wont-let-me-push-changes) 
* [FINK-41](https://linear.app/opral/issue/FINK-41/not-able-to-push-translations) 
* [FINK-51](https://linear.app/opral/issue/FINK-51/failed-to-push-changes)
* [https://discord.com/channels/897438559458430986/1247865778976329821/1247891530203791370](https://discord.com/channels/897438559458430986/1247865778976329821/1247891530203791370) 

### Proposal

Lix should provide an API that detects if Lix can push to the repo<br><br>This way Fink (and other apps) can prompt to update the permissions (user is the owner), contact the repo's owner (user is a collaborator) or fork the project (if not disabled [LIX-57](https://linear.app/opral/issue/LIX-57/detect-users-fork-permission) ).

**Comment by samuelstroschein** [comment]
not relevant for lix on sqlite anymore
