### ISSUE TITLE
is a undo stack for working/draft changes wanted?

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#29]
### Context

Lix can't undo (uncommitted) changes. 

### Research question 

Should lix support undoing (uncommitted) changes? 

Based on yes or no, the internal implementation of lix changes. Hence, it would be good to know now if lix should support an undo stack.

**Comment by samuelstroschein** [comment]
Gut feeling is yes. Undoing changes and showing the history of "draft" changes seems beneficial as it avoids creating commits if no commit is desired ([LIX-125](https://linear.app/opral/issue/LIX-125/whats-the-purpose-of-a-commit)).

**Comment by NiklasBuchfink** [comment]
In all apps where I have a real editing process, users could benefit from an undo + redo feature.<br>If it is easy to implement, this could be the "one-trick-pony" feature that is driving adoption. This is similar to how Parrot is just used as a language switch for 90% of the users, but it is the reason the other 10% discovered this tool. It would be awesome to have such a feature in Lix. cc @jannes.blobel

**Comment by samuelstroschein** [comment]
Concluded the question as "yes", and trivial to implement with [LIXDK-131](https://linear.app/opral/issue/LIXDK-131/dont-overwrite-draft-changes).
