### ISSUE TITLE
`URI` as primitive in `@lix-js/fs`

### ISSUE THREAD

**Issue by felixhaeberle** [opral/lix-sdk#3]
## Problem

We often have to deal with paths inside multi env code like the new `cross-sell` packages which aim to simpify the cross-sell of our apps with access to the `fs`. 

The operations done on the fs often requires path manipulation and therefore we introduced `normalizePath` & `normalPath` – both of them are poorly executed because no higher approach has yet been found to tackle paths multi env (node/web etc.)

## Proposal

Come up with a solution like 

```ts
import path from "@lix-js/path"

// use it in nodejs
path.join()

// use it on the web
path.join()
```

I'm surely only scratching the surface here, but the bugs in opral/monorepo#2184 alike seems that there is an urge to introduce `@lix-js/path`.

**Comment by samuelstroschein** [comment]
@felix.haeberle here you go

**Comment by samuelstroschein** [comment]
closing because irrelevant for lix on sqlite / is replaced by #30
