### ISSUE TITLE
Lix does not track if I redo changes manually

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/lix-sdk#34]
When I use fink2 and do an change it gets shown as a change. If I redo the change manually it is still a change. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/88123e6e-7efb-49b7-9aa1-09b076093f3f/93800d66-e520-4f5e-8999-2535528c1321?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC84ODEyM2U2ZS03ZWZiLTQ5YjctOWFhMS0wOWIwNzYwOTNmM2YvOTM4MDBkNjYtZTUyMC00ZjVlLTg5OTktMjUzNTUyOGMxMzIxIiwiaWF0IjoxNzIzNDY0OTM2LCJleHAiOjMzMjk0MDI0OTM2fQ.ANjVJiwBnfs9tRl3WszIYHwyztW9LXXLKylWKWvHqTk " alt="image.png" width="1330" height="434" />

**Comment by samuelstroschein** [comment]
@nils.jacobsen @niklas.buchfink jan is working on fixing this

**Comment by NilsJacobsen** [comment]
@jan.johannes oh jap sorry for the confusion

**Comment by samuelstroschein** [comment]
closed by https://github.com/opral/monorepo/pull/3059#discussion_r1715330278
