### ISSUE TITLE
remove `file_internal` in favor of simplified change queue

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#35]
### Context

The change queue could be implemented without a `file_internal` table.

* Uncertainty exists if the change queue implementation in [https://github.com/opral/monorepo/pull/3061](https://github.com/opral/monorepo/pull/3061) is the "simplest/best" way to go.
  * [https://github.com/opral/monorepo/pull/3061#pullrequestreview-2238335973](https://github.com/opral/monorepo/pull/3061#pullrequestreview-2238335973)
  * [https://discord.com/channels/897438559458430986/1267939224041291776/1267961744718958717](https://discord.com/channels/897438559458430986/1267939224041291776/1267961744718958717)
* It certainly leads to bugs because writing to file and file_internal behaves differentely.

### Proposal

Remove `file_internal` by storing both old and new file values in the queue itself.

* no views
* no edge cases
* beautiful simple

**Comment by samuelstroschein** [comment]
The `file_internal` implementations leads to bugs. An argument to go with a copy old, new file data implementation. 

The code below has two problems: 

1. I forgot to use settled, expecting that file writes which happen in `resolveConflict` are immediately written "to disk". 
2. Even using `settled` didn't work. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/3b3e4bde-9cc6-4393-af1c-f5d70dfdf86e/2195abc1-a13c-4e1e-ae90-4e919d8962b8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8zYjNlNGJkZS05Y2M2LTQzOTMtYWYxYy1mNWQ3MGRmZGY4NmUvMjE5NWFiYzEtYTEzYy00ZTFlLWFlOTAtNGU5MTlkODk2MmI4IiwiaWF0IjoxNzI0NTM1ODY5LCJleHAiOjMzMjk1MDk1ODY5fQ.Z2No1gd6WGF8ZH1iRqIqkYmqWS6-39B7jCStu5GJVSk " alt="CleanShot 2024-08-24 at 17.40.09@2x.png" width="1474" height="876" />

The fix was to write to the `file` table instead of `file_internal`. Point being, the ergonomics around

**Comment by samuelstroschein** [comment]
Just ran into another problem with `file_internal`:

```
SQLite3Error: SQLITE_ERROR: sqlite3 result code 1: cannot UPSERT a view. 
```

If i am not mistaken, the current queue implementation will prevent upserts. No matter how we design the public API for files. The two options of 1) writing to a file view that triggers the queue, or 2) writing to "the actual table" and bypassing the queue will always lead to a "I want to upsert but don't bypass the queue" problems.

**Comment by samuelstroschein** [comment]
The flaky tests with 'driver destroyed" are coming from the current change queue implementation [https://github.com/opral/monorepo/pull/3093/commits/75fe4be582f839485b2b4f75b05dd617d561f222](https://github.com/opral/monorepo/pull/3093/commits/75fe4be582f839485b2b4f75b05dd617d561f222).

**Comment by martin-lysk** [comment]
Findings:

**Current implementation of change queue is broken with branch implementation:**

Changes from state a -> b are extracted asynchronously via the change queue, the current banch is read after the changes have been extracted [https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/lix/file-handlers.ts#L61](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/lix/file-handlers.ts#L61)

\-> This means if one switches a branch while the queue is processing the change, those are compute for the new branch instead

**Deletion is currently bypassing the change queue**

[https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/database/apply-schema.ts#L105-L106](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/database/apply-schema.ts#L105-L106)

**We use the internal_file table to bypass the change queue:**

* during [merge](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/lix/merge.ts#L81)
* in[ conflict resolution ](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/change-conflict/resolve-conflict-by-selecting.test.ts#L51) scenarios
* during [apply changes](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/plugin/apply-changes.ts#L67)

how should we deal with this if have a "real" table (deactivating / activating triggers?)

**The change queue writes to the internal_file table after an entry in the queue was processed**

\-> this could lead to side effects if something else operatates on the internal file table in during queue is not idle

Also we should think about js <-> sqlite land border crossings [see](https://github.com/opral/monorepo/blob/b73c1cb872a1a6a1e26fb161615c526974e7733b/packages/lix-sdk/src/lix/file-handlers.ts#L85-L86)
