### ISSUE TITLE
`old` `neu` alternative?

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#44]
### Context

The terms are used in diffing and derived from SQL. `new` is a reserved keyword in JS, leading to the easter egg `neu`. It's annoying though because one forgets that `neu` is used instead of `new`. 

### Proposal

Can we come up with a better "this is the old and this is the new change" terminology?

**Comment by samuelstroschein** [comment]
`before` `after` ?

**Comment by samuelstroschein** [comment]
@martin.lysk1 choose before after ? seems logical to me

**Comment by martin-lysk** [comment]
sounds good to me
